2018-09-24T06:09:47.370Z INFO    :LoadModule               :loadModule()              Loading composer-wallet-filesystem from /usr/local/lib/node_modules/composer-playground/node_modules/composer-wallet-filesystem {}$
2018-09-24T06:09:47.685Z INFO    :PlaygroundAPI            :createServer()            Playground API started on port 8080 {}$
2018-09-24T06:10:18.238Z INFO    :LoadModule               :loadModule()              Loading composer-wallet-filesystem from /usr/local/lib/node_modules/composer-playground/node_modules/composer-wallet-filesystem {}$
2018-09-24T06:10:18.387Z INFO    :PlaygroundAPI            :createServer()            Playground API started on port 9090 {}$
2018-09-24T06:10:29.200Z INFO    :PlaygroundAPI            :createServer()            Client with ID '0_vSjEOkxdn1wS2iAAAA' on host '::ffff:10.255.0.2' connected {}$
2018-09-24T06:10:30.866Z INFO    :PlaygroundAPI            :createServer()            Client with ID 'mwYDSCWtEvEjrkX3AAAB' on host '::ffff:10.255.0.2' connected {}$
2018-09-24T06:10:31.863Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2018-09-24T06:10:35.869Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Using this connection manager  {"0":{"connectionProfileManager":{}}}$
2018-09-24T06:10:37.392Z WARN    :HLFConnection            :_checkCCListener()        could not find any connected event hubs out of 3 defined hubs to listen on for chaincode events {}$
2018-09-24T06:10:50.432Z INFO    :PlaygroundAPI            :createServer()            Client with ID '0_vSjEOkxdn1wS2iAAAA' on host '::ffff:10.255.0.2' disconnected (transport close) {}$
2018-09-24T06:10:50.440Z INFO    :PlaygroundAPI            :createServer()            Client with ID 'mwYDSCWtEvEjrkX3AAAB' on host '::ffff:10.255.0.2' disconnected (transport close) {}$
2018-09-24T06:10:57.017Z INFO    :PlaygroundAPI            :createServer()            Client with ID 'SGzKnFMJ3wGDtylmAAAC' on host '::ffff:10.255.0.2' connected {}$
2018-09-24T06:11:13.554Z INFO    :PlaygroundAPI            :createServer()            Client with ID 'JM5e1r59pfkS5yNyAAAD' on host '::ffff:10.255.0.2' connected {}$
2018-09-24T06:11:17.538Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2018-09-24T06:11:38.671Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2018-09-24T06:24:23.429Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:24:23.525Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:24:23.601Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:24:23.601Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist {}$
2018-09-24T06:24:23.601Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist {}$
2018-09-24T06:24:23.602Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist {}$
2018-09-24T06:24:23.604Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-09-24T06:24:23.606Z ERROR   :ConnectorServer          :connectionInvokeChainCode {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The specified query does not exist\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-09-24T06:44:52.156Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:44:52.157Z WARN    :HLFQueryHandler          :queryChaincode()          Peer  Peer : {url:grpcs://192.168.1.158:9051} failed to respond. Error: 14 UNAVAILABLE: TCP Read failed {}$
2018-09-24T06:44:52.157Z ERROR   :HLFQueryHandler          :queryChaincode()          {"message":"No peers available to query. last error was Error: 14 UNAVAILABLE: TCP Read failed","stack":"Error: No peers available to query. last error was Error: 14 UNAVAILABLE: TCP Read failed\n    at HLFQueryHandler.queryChaincode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfqueryhandler.js:108:30)\n    at <anonymous>"}$
2018-09-24T06:44:52.158Z ERROR   :ConnectorServer          :connectionQueryChainCode( {"message":"No peers available to query. last error was Error: 14 UNAVAILABLE: TCP Read failed","stack":"Error: No peers available to query. last error was Error: 14 UNAVAILABLE: TCP Read failed\n    at HLFQueryHandler.queryChaincode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfqueryhandler.js:108:30)\n    at <anonymous>"}$
2018-09-24T06:45:10.162Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:45:10.163Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:45:10.165Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed
    at new createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)
    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:583:15 {}$
2018-09-24T06:45:10.165Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed {}$
2018-09-24T06:45:10.167Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed {}$
2018-09-24T06:45:10.167Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed {}$
2018-09-24T06:45:10.168Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-09-24T06:45:10.170Z ERROR   :ConnectorServer          :connectionInvokeChainCode {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\nResponse from attempted peer comms was an error: Error: 14 UNAVAILABLE: TCP Read failed\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-09-24T06:46:58.076Z ERROR   :HLFConnectionManager     :fabric-client()           [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: TCP Read failed\n    at createStatusError (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:64:15)\n    at ClientDuplexStream._emitStatusIfDone (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:270:19)\n    at ClientDuplexStream._receiveStatus (/usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:248:8)\n    at /usr/local/lib/node_modules/composer-playground/node_modules/grpc/src/client.js:804:12" {}$
2018-09-24T06:46:58.080Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: SERVICE_UNAVAILABLE","stack":"Error: Error trying invoke business network. Error: SERVICE_UNAVAILABLE\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-09-24T06:46:58.081Z ERROR   :ConnectorServer          :connectionInvokeChainCode {"message":"Error trying invoke business network. Error: SERVICE_UNAVAILABLE","stack":"Error: Error trying invoke business network. Error: SERVICE_UNAVAILABLE\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-09-24T06:49:58.798Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-09-24T06:49:58.799Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) {}$
2018-09-24T06:49:58.799Z WARN    :HLFQueryHandler          :queryChaincode()          query payload returned an error: Error: REQUEST_TIMEOUT {}$
2018-09-24T06:49:58.799Z ERROR   :ConnectorServer          :connectionQueryChainCode( {"message":"REQUEST_TIMEOUT","stack":"Error: REQUEST_TIMEOUT\n    at Timeout._onTimeout (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:124:19)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)"}$
2018-09-24T06:50:27.639Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-09-24T06:50:27.644Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) {}$
2018-09-24T06:50:27.646Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-09-24T06:50:27.647Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) {}$
2018-09-24T06:50:27.648Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
2018-09-24T06:50:27.650Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
2018-09-24T06:55:27.711Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: Failed to receive commit notification from 192.168.1.158:7051 for transaction '494e5b9ddfcc6d2f3bd8580707a1bb14bea136d4fb81f8c63ffe06adf5f0b1cc' within the timeout period","stack":"Error: Error trying invoke business network. Error: Failed to receive commit notification from 192.168.1.158:7051 for transaction '494e5b9ddfcc6d2f3bd8580707a1bb14bea136d4fb81f8c63ffe06adf5f0b1cc' within the timeout period\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-09-24T06:55:27.715Z ERROR   :ConnectorServer          :connectionInvokeChainCode {"message":"Error trying invoke business network. Error: Failed to receive commit notification from 192.168.1.158:7051 for transaction '494e5b9ddfcc6d2f3bd8580707a1bb14bea136d4fb81f8c63ffe06adf5f0b1cc' within the timeout period","stack":"Error: Error trying invoke business network. Error: Failed to receive commit notification from 192.168.1.158:7051 for transaction '494e5b9ddfcc6d2f3bd8580707a1bb14bea136d4fb81f8c63ffe06adf5f0b1cc' within the timeout period\n    at HLFConnection.invokeChainCode (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:999:30)\n    at <anonymous>"}$
2018-09-24T09:28:15.825Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2018-09-24T09:33:19.234Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2018-09-24T09:33:19.237Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) {}$
2018-09-24T09:33:19.241Z WARN    :HLFQueryHandler          :queryChaincode()          query payload returned an error: Error: REQUEST_TIMEOUT {}$
2018-09-24T09:33:19.245Z ERROR   :HLFConnection            :ping()                    {"message":"Error trying to ping. Error: REQUEST_TIMEOUT","stack":"Error: Error trying to ping. Error: REQUEST_TIMEOUT\n    at _checkRuntimeVersions.then.catch (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:813:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-09-24T09:33:19.249Z ERROR   :ConnectorServer          :connectionPing()          {"message":"Error trying to ping. Error: REQUEST_TIMEOUT","stack":"Error: Error trying to ping. Error: REQUEST_TIMEOUT\n    at _checkRuntimeVersions.then.catch (/usr/local/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:813:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
